### ISSUE TITLE
Vibration Sensor Interface

### ISSUE THREAD

**Issue by mikeshams** [simranflora28/CAPSTONE_EMBT_WINTER2020#4]
What issues did you face? How to resolve?

**Comment by Jasmeet07** [comment]
During the interfacing of vibration sensor, i didn't face any issue in the programming but the vibrator sensor stopped working we tried testing it again but didn't get any output. Also, we tried to connect it to the other GPIOs. Therefore, we have to replace the vibrator sensor with the new one.
