### ISSUE TITLE
Power Management

### ISSUE THREAD

**Issue by mikeshams** [simranflora28/CAPSTONE_EMBT_WINTER2020#6]
How to make a BBB go to a deep sleep mode?

**Comment by Kirangill4** [comment]
The sleep modes supported by the beaglebone black are
1. mem
2. disk
3. standby
4. freeze
The "mem" power state corresponds to "deepsleep0" state of the processor. To put the beagleboneblack into the deep sleep the following command is used 
echo mem>/sys/power/state
As the project is related to the security therefore, it is not feasible to put it into the deep sleep mode but in our project standby sleep mode is used.
Reference:  [https://www.mail-archive.com/beagleboard@googlegroups.com/msg55044.html](url)
